### ISSUE TITLE
ctk: management section of the component envelope to support dependentAPIs (as well as exposedAPIs)

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-component-ctk#25]
## Description

At the moment, the coreFunction of the component envelope allows you to specify `exposedAPIs` as well as `dependentAPIs`, but the management section only has the facility to have a list of exposedAPIs. Should we extend the management section to specify `exposedAPIs` as well as `dependentAPIs` to bring it into line with the coreFunction?

FYI: The security section also requires a specific 'partyrole' property that is not in any list.

**Comment by LesterThomas** [comment]
At the moment, the event notifications are in their own section. Will it be possible to expose and subscribe to management events and security events?

**Comment by brian-burton** [comment]
I agree that we should allow `exposedAPIs` and `dependentAPIs` across the `coreFunction`, `management` and `security` sections, but they should follow the same format so that there's no structural difference between them. However, the `partyrole` API is mandatory in the security section, so it might be a good idea to harmonise them by making `exposedAPIs` and `dependentAPIs` arrays instead of a list.

Instead of:

```
exposedAPIs: 
    - name: productcatalogmanagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
      implementation: {{.Release.Name}}-prodcatapi
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productCatalogManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productCatalogManagement/v4/docs
      port: 8080
```

...we would have:

```
exposedAPIs: 
      productcatalogmanagement
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
        implementation: {{.Release.Name}}-prodcatapi
        apitype: openapi
        path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productCatalogManagement/v4
        developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productCatalogManagement/v4/docs
        port: 8080
```

Then, in CTK we could test to ensure the `security.exposedAPIs` section has an element called `partyrole`.
